task:
  matrix:
  - arm_container:
      image: ghcr.io/getsentry/prebuilt-pythons-manylinux-arm64-ci
  - macos_instance:
      image: ghcr.io/cirruslabs/macos-monterey-base:latest
  env:
    matrix:
    - {PY: 3.8.15, BUILD: '0'}
    - {PY: 3.9.15, BUILD: '0'}
    - {PY: 3.10.8, BUILD: '0'}
    - {PY: 3.11.0, BUILD: '0'}
  name: ${CIRRUS_OS}-${PY}-arm64
  build_script: python3 -um build_binary $PY --build $BUILD
  validate_script: python3 -um validate
  artifacts:
    path: dist/*
