name: build
on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  build:
    strategy:
      matrix:
        include:
        - {os: macos-latest, py: 3.8.17, build: 0}
        - {os: macos-latest, py: 3.9.17, build: 0}
        - {os: macos-latest, py: 3.10.11, build: 0}
        - {os: macos-latest, py: 3.11.3, build: 0}
        - {os: ubuntu-latest, py: 3.8.17, build: 0}
        - {os: ubuntu-latest, py: 3.9.17, build: 0}
        - {os: ubuntu-latest, py: 3.10.11, build: 0}
        - {os: ubuntu-latest, py: 3.11.3, build: 0}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: python3 -um build_binary ${{ matrix.py }} --build ${{ matrix.build }}
    - run: python3 -um validate
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}-${{ matrix.py }}
        path: dist/*

  cirrus:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        os: [darwin, linux]
        py: [3.8.17, 3.9.17, 3.10.11, 3.11.3]
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
    - uses: getsentry/action-wait-for-cirrus@v1.0.0
      with:
        task: ${{ matrix.os }}-${{ matrix.py }}-arm64
      timeout-minutes: 30
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}-${{ matrix.py }}-arm64
        path: dist/*

  collect-and-deploy:
    needs: [build, cirrus]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SENTRY_DEV_INFRA_ASSETS_WRITER }}
    - run: yes | gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"
    - run: bin/upload-artifacts
